import type { Metadata } from "next";
import { Tenor_Sans, Public_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import MobileBar from "@/components/nav/MobileBar";
import NavbarWrapper from "@/components/layout/NavbarWrapper";
import { getFooterBottomNavigation, getFooterNavigation } from "@/lib/wordpress/menu";
import { getThemeSettings } from "@/lib/wordpress/themeSettings";
import { LanguageProvider } from "@/lib/i18n/LanguageContext";

const tenorSans = Tenor_Sans({
  variable: "--font-tenor-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const [footerMenuItems, bottomMenuItems, themeSettings] = await Promise.all([
    getFooterNavigation(),
    getFooterBottomNavigation(),
    getThemeSettings(),
  ]);

  return (
    <html
      lang="en"
      className={`${tenorSans.variable} ${publicSans.variable} h-full scroll-smooth antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>

          <NavbarWrapper />

          <main>
            {children}
          </main>
          <Footer
            menuItems={footerMenuItems}
            bottomMenuItems={bottomMenuItems}
            themeSettings={themeSettings}
          />
          <MobileBar themeSettings={themeSettings} />
        </LanguageProvider>

      </body>
    </html>
  );
}
